# Results

```{r, message=FALSE, echo=FALSE, results='hide'}
library(tidyverse)
```

## COVID Data Exploration

```{r, message=FALSE}
df_covid = read.csv("data/covid.csv") %>% select(-X)
summary(df_covid)
```

### Cleveland Dot Plot

```{r, fig.height=8, fig.width=6}
df_covid %>% arrange(desc(Total.Death)) %>% head(50) %>% 
   mutate("Country.Region" = fct_reorder(Country.Region, Total.Death)) %>% 
  ggplot(aes(x = Total.Death, y = Country.Region)) + 
  geom_point(color = "#D75D47", size = 2) +
  labs(title = 'COVID-19 Cumulative Death of Countries',
       y = '', x = "Total Death")
```

### Heatmap

```{r}
df_map = read.csv("data/Location.csv")
df_covid %>% left_join(df_map, 
                       by = c("Country.Region" = "Country")) %>% 
  ggplot(aes(x = long, y = lat, group = group, text = Country.Region)) +
  geom_polygon(aes(fill = Total.Death), color = "#AAABAC") + 
  scale_fill_gradient(low = "#FBD588", high = "#F55536") +
  labs(title = "COVID-19 Cumulative Death World Heatmap",
       fill = "Total Death", x = "", y = "")
  
```





