# Conclusion

## Disaster Data

Through the above analysis of disasters, we can find the following points. First of all, there are more natural disasters than technological disasters in this dataset, and we think it's because of a problem with its data collection process. It did not include disasters caused by technology such as war, firearm death, etc.. We guessed that it may be because this type of data is difficult to count. Given the above situation, we found that in terms of the frequency of disasters, technological disasters are all very high. But if we look at deaths and economic losses, natural disasters are firmly at the forefront. The reason for this, we believe, may be that the scale of natural disasters far exceeds that of technological disasters, so although technological disasters occur frequently, their destructive power is still less than the natural disasters. Of course, for the overall trend, deaths and economic losses are still positively correlated with the frequency of disasters. Secondly, the more developed countries are more in place for the protection of personnel.




## Comparing Disaster Damage and Covid

Based on our analysis, we want to see some pattern between COVID and other disaster for different countries. As we discovered, most of the developed countries have similar or the same pattern for COVID and other disaster. But for some of the developing countries and countries from Oceania, it's not the case. It's because of both geographical and economical reasons. 

COVID is actually the reason we are interested in disaster analysis in the first place. It has had a huge impact in our daily life and in economic world. But after getting the disaster data, an interesting finding is that for disaster caused by infectious diseases like COVID, the damage is usually 0, because these type of disaster does not really have damage to our tangible assets like houses or cars, and other emotional damage, potential damage, and damage to our intangible assets are hard to count by money. We in the end used GDP as an indicate to COVID economic damage, and the number is huge, which makes us wonder if there are huge losses from former diseases that were not accounted for. The things we have lost from all disasters are far beyond the counting from this dataset. It is important to study and analyze disasters - the possible causes and patterns of natural disasters and the reasons for technology disasters - so that we can better maintain the environment of the world we lived in. 