--- 
title: "Disaster Analysis"
author: 
  - Jiachen Liu
  - Hao Chang
  - Yihui Xie
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
---
--- 
title: "Disaster Analysis"
author: 
  - Jiachen Liu
  - Hao Chang
  - Yihui Xie
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
---

# Introduction

As the pandemic grow rapidly after 2020 and developed a kind of stable pattern nowadays, it has a great influence on the human livings and other activities. Actually this is not the only disaster that had a great influence on humans' live. There are several big disaster that are greatly recorded in the history. For example, the Valdivia Earthquake Strikes Chile, the Chernobyl nuclear disaster, the Indian Ocean Tsunami etc. They've all made a big damage on humans' life as well as economic.

We are interested in the disaster damage pattern in different region and different time. Is there any clustering patterns? Is there a inside seasonal pattern? Is there any relation between different disasters? These are all questions that researchers are interested in. We want to use data visualization method to have an intuitive understanding of these patterns.

Also, as we want to know more about the pattern of Covid-19, for we can know about the real world based on this, we also want to compare the Covid-19 pattern and other disaster. It might give us a internal understanding of nowadays pandemic.





<!--chapter:end:index.Rmd-->


# Data sources

Placeholder


## Disester Data
## COVID Data
## GDP Data

<!--chapter:end:02-data.Rmd-->


# Data transformation

Placeholder


## Disaster Data
### checking the country name
### Manual Adjustments
## Covid Data
## GDP time series data

<!--chapter:end:03-cleaning.Rmd-->


# Missing values

Placeholder


## Disaster dataset
### By row
### By Column
### By Value
## Covid Dataset
## GDP Dataset
### For countries
### For Year

<!--chapter:end:04-missing.Rmd-->

# Results

<!--chapter:end:05-results.Rmd-->

# Interactive component
```{r, message=FALSE}
library(shiny)
runApp('App.R')
```




<!--chapter:end:06-interactive.Rmd-->

# Conclusion


<!--chapter:end:07-conclusion.Rmd-->

